plugins {
    id "com.android.application"
}

android {
    namespace "com.example.therapyschedule"
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "com.example.therapyschedule"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}
